[package]
name = "zed_composer_support"
version = "0.2.4"
edition = "2021"
publish = false
license = "MIT"

[workspace]
members = ["server"]
default-members = ["."]
resolver = "2"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = "symbols"
